## Numpy

In [1]:
import numpy as np

**Ejercicio 1**: Responder las siguientes preguntas:

* ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.

In [4]:
lista = [0,1,2,3,4,5]
arreglo = np.array(lista)
print(lista)
print(arreglo)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


In [7]:
#Otras formas: ejemplo de creación de listas 
lista = list(range(8))
lista_2 = []
for i in range(8):
    lista_2.append(i)
print(lista)
print(lista_2)
#Y facilidad de creación de un arreglo con Numpay
arreglo = np.arange(8)
print(arreglo)

[0, 1, 2, 3, 4, 5, 6, 7]
[0, 1, 2, 3, 4, 5, 6, 7]
[0 1 2 3 4 5 6 7]


* ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.


In [10]:
#SUMAR UN ELEMENTO EN UN ARREGLO
arreglo += 1
arreglo

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#SUMAR UN ELEMENTO EN UN LISTA
lista + 1 
#DA ERROR

In [12]:
#ELEVAR AL CUADRADO
arreglo**2
arreglo

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#ELEVAR AL CUADRADO
lista**2
#ERROR

In [13]:
#SUMAR LOS ELEMENTOS PROPIOS
print(arreglo.sum())

52


In [16]:
#SUMAR LOS ELEMENTOS PROPIOS
sum(lista)
#print(lista.sum()) ----> ERROR

28

In [17]:
#CONOCER CUANTOS ELEMENTOS TENEMOS
print(arreglo)
arreglo.shape

[ 3  4  5  6  7  8  9 10]


(8,)

In [19]:
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]] . Shape = (3, 6) 



In [18]:
#CONOCER CUANTOS ELEMENTOS TENEMOS
len(lista)

8

* ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.

In [20]:
#¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)?

print('Arreglo de (n,)')
arreglo = np.array([1,2,3,4,5,6])
print(arreglo,'. Shape =', arreglo.shape, "\n") # "\n" imprime un salto de linea

print('Arreglo de (2,n)')
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

print('Arreglo de (n,1)')
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo.T,'. Shape =', arreglo.T.shape, "\n")   #notar .T, que significa transpuesto

Arreglo de (n,)
[1 2 3 4 5 6] . Shape = (6,) 

Arreglo de (2,n)
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]] . Shape = (2, 6) 

Arreglo de (n,1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 



In [21]:
### EXTRA 1###
#Trasponer no es la unica forma de crear un arreglo de forma (n,1)'''
arreglo = np.array([[1],[2],[3],[4],[5],[6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape)   #notar .T, que significa transpuesto

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1)


**Ejercicio 2**:
* Escribir un arreglo con números enteros del 0 al 9. Pista: arange

In [22]:
arreglo_1 = np.arange(0,10)
print(arreglo_1)

[0 1 2 3 4 5 6 7 8 9]


* Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

In [26]:
arreglo_2 = np.linspace(0,9, 100)
print(arreglo_2)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.
 1.09090909 1.18181818 1.27272727 1.36363636 1.45454545 1.54545455
 1.63636364 1.72727273 1.81818182 1.90909091 2.         2.09090909
 2.18181818 2.27272727 2.36363636 2.45454545 2.54545455 2.63636364
 2.72727273 2.81818182 2.90909091 3.         3.09090909 3.18181818
 3.27272727 3.36363636 3.45454545 3.54545455 3.63636364 3.72727273
 3.81818182 3.90909091 4.         4.09090909 4.18181818 4.27272727
 4.36363636 4.45454545 4.54545455 4.63636364 4.72727273 4.81818182
 4.90909091 5.         5.09090909 5.18181818 5.27272727 5.36363636
 5.45454545 5.54545455 5.63636364 5.72727273 5.81818182 5.90909091
 6.         6.09090909 6.18181818 6.27272727 6.36363636 6.45454545
 6.54545455 6.63636364 6.72727273 6.81818182 6.90909091 7.
 7.09090909 7.18181818 7.27272727 7.36363636 7.45454545 7.54545455
 7.63636364 7.72727273 7.81818182 7.90909091 8.         8.09090909
 8.18181818

**Ejercicio 3**:
* Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son divisibles por 3<br>
Pista: mask

In [28]:
a = np.arange(10,101)
a2=(a%3==0)
b=a[a2]
print(b)

[12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81
 84 87 90 93 96 99]


In [29]:
mascara = ((a%2)==0) #Creamos la máscara (filtro)

In [30]:
mascara

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True])

**Ejercicio 4**:

* Crear un arreglo de ceros de `shape` (5,10).

In [31]:
zeros = np.zeros((5,10), dtype = int)
zeros

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

* Reemplazar la segunda y cuarta fila con unos

In [32]:
zeros[[1,3],:] = 1
zeros

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

* Reemplazar la tercera y octava columna con dos (2).

In [33]:
zeros[:,[2,7]]=2
zeros

array([[0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
       [1, 1, 2, 1, 1, 1, 1, 2, 1, 1],
       [0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
       [1, 1, 2, 1, 1, 1, 1, 2, 1, 1],
       [0, 0, 2, 0, 0, 0, 0, 2, 0, 0]])

EJERCICIOS EXTRAS DE LOS 100

In [2]:
#Q2.  Create a 1D array of numbers from 0 to 9
b=np.arange(0,10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
#Q3. Create a 3×3 numpy array of all True’s
matriz=np.random.random((3,3))
mascara=((matriz%1!=0))
mascara

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
#Q4. Extract all odd numbers from arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#> array([1, 3, 5, 7, 9])
arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [5]:
#Q5. Replace all odd numbers in arr with -1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr[arr%2==1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [6]:
#Replace items that satisfy a condition without affecting the original array?
#Q6. Replace all odd numbers in arr with -1 without changing arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#out
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
#arr
#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out=np.where(arr%2==1,-1,arr) #Condicion, x, y -->  
                #Si se cumple, se devuelve el valor de x. Si no se cumple, el de y.
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [7]:
#Reshape array
#Q7. Convert a 1D array to a 2D array with 2 rows
a=np.arange(10)
#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])
a2=a[np.newaxis,5:]
print(a2)
a.reshape(2,5) # Setting to -1 automatically decides the number of cols


[[5 6 7 8 9]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
#Stack two arrays vertically?
#Q8. Stack arrays a and b vertically
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])
np.concatenate([a,b],axis=0)
np.r_[a,b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [9]:
#Stack two arrays horizontally?
#Q9. Stack the arrays a and b horizontally.
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
np.concatenate([a,b],axis=1)
np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [10]:
#Generate custom sequences in numpy without hardcoding?
#Q10. Create the following pattern without hardcoding. Use only numpy functions and the below input array a
a = np.array([1,2,3])
#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
np.r_[np.repeat(a, 2), np.tile(a,3)]

array([1, 1, 2, 2, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
np.intersect1d #Intercepta valores entre dos arrays
np.setdiff1d #Elimina todos los elementos que existen en otro array
np.where(a == b) #Nos permite obtener las posiciones donde los elementos se repiten
a[(a >= 5) & (a <= 10)] #Nos permite pbtener los elementos en ese rango del array

In [11]:
#How to make a python function that handles scalars to work on numpy arrays?
#Difficulty Level: L2
#Q15. Convert the function maxx that works on two scalars, to work on two arrays.
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.]

In [12]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max=np.vectorize(maxx,otypes=[int]) #Vectorize para poder usar una funcion 
pair_max(a, b)

array([6, 7, 9, 8, 9, 7, 5])

In [13]:
arr = np.arange(9).reshape(3,3) #Itercambiando columnas 
print(arr)
a2=arr[:,[1,0,2]] 
print(a2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [14]:
arr = np.arange(9).reshape(3,3) #Intercambiando filas 
print(arr)
a3=arr[[2,0,1],:]
print(a3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [0 1 2]
 [3 4 5]]


In [15]:
#Q. Reverse the rows of a 2D array arr.
arr = np.arange(9).reshape(3,3)
arr[ : :-1] 

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])